### ISSUE TITLE
Issues with Julia 1.11

### ISSUE THREAD

**Issue by JordiManyer** [ericneiva/Algoim.jl#5]
@ericneiva have you tried using the package with Julia 1.11? I get a precompilation error, I think coming from the artifact: 

```julia
ERROR: LoadError: algoimWrapper_jll not available on this platform
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ ~/.julia/packages/Algoim/9wHKA/src/Algoim.jl:9
 [3] include
   @ ./Base.jl:557 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
   @ Base ./loading.jl:2790
 [5] top-level scope
   @ stdin:5
in expression starting at /home/user1/.julia/packages/Algoim/9wHKA/src/Algoim.jl:1
in expression starting at stdin:5
ERROR: LoadError: Failed to precompile Algoim [0eb9048c-21de-4c7a-bfac-056de1940b74] to "/home/user1/.julia/compiled/v1.11/Algoim/jl_RbemJm".
```

It was working well for Julia 1.9. Do you have any idea of what might be going on?

**Comment by ericneiva** [comment]
Hi, @JordiManyer, the new version of Algoim (0.2.2) --just released-- should work with Julia 1.11.

An update of GE is also on the way. See https://github.com/gridap/GridapEmbedded.jl/pull/97

Let me know if you have any issue with the update :)

**Comment by ericneiva** [comment]
FYI @zjwegert

**Comment by JordiManyer** [comment]
Ok great! Thanks @ericneiva
